spring.datasource.driverClassName=${DB_DRIVER:org.postgresql.Driver}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/backlog_games}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:sua_senha_local_aqui}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
api.security.token.secret=${JWT_SECRET:minha-senha-super-secreta-de-desenvolvimento}